version: 0.2
env:
  variables:
    ENV_NAME: "prod"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "install nodejs"
  pre_build:
    commands:
      - echo "pre build"
  build:
    commands:
      - echo "start build"
      - node -v
      - sh test.sh
      - echo $TEST
      - echo $ENV_NAME
  post_build:
    commands:
      - echo "finished the build"
  
artifacts:
  files:
    - 'appspec.yml'
    - 'index.html'
  name: myweb-release