version: 0.2
phases:
  install:
    runtime-version:
      nodejs: 12
    commands:
      - echo "intall the runtime"
  pre_build:
    commands:
      - echo "pre-build"
  build:
    commands:
      - echo "start"
      - node -v
  post_build:
    commands:
      - echo "build over"
  artifacts:
    files:
      - '**/*'
    name: myweb-release