version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "install nodejs"
  pre_build:
    commands:
      - echo "pre build"
  build:
    commands:
      - echo "start build"
      - node -v
  post_build:
    commands:
      - echo "finished the build"
  
artifact:
  files:
    - '**/*'
  name: myweb-release