version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "intall the runtime"
  pre_build:
    commands:
      - echo "pre-build"
  build:
    commands:
      - echo "start"
      - node -v
      - sh test.sh
      - echo "-------------------"
      - echo $AWS_DEFAULT_REGION
      - echo "-------------------"
  post_build:
    commands:
      - echo "build over"
artifacts:
  files:
    - '**/*'
  name: myweb-release
